# Import de bibliotecas

In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import cluster, neighbors, svm, metrics, preprocessing

# Abertura da base Iris

In [31]:
df = pd.read_csv('base.csv', encoding = "ISO-8859-1")                   


# Criação dos arquivos de treinamento e tese

In [37]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["variety"] #define o atributo alvo da base para o treinamento
testTarget = testSample["variety"] #define o atributo alvo da base para o teste


del testSample["variety"]
del trainSample["variety"]


# Usando o K-NN

In [38]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

# Avaliando o modelo

In [36]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)



K-NN
Acurácia: 0.93
Matriz de Confusão:
 [[10  0  0]
 [ 0 12  1]
 [ 0  1  5]]
